notion:
  token:
  version: 2022-06-28
  databases_url:

system:
  rss_get_timer: 1800
  notion_get_timer: 1200
  notion_memos_get_timer: 1000
  #db: ./db/rss.db
  db:
  len: 1000 #摘要字数
  port: :8899

sql_condition:
  rands_time: 48 HOUR
  rands_count: 3
  rank_time: 30 DAY